typography_spectrum: 0.9332455788390471
color:
  brandStrength: 0.5269773786166443
  lightness: 0.2560679254186626
  saturation: 0.3108205722229057
  rhythmicContrast: 0.9952563867504054
  brandColors:
    - '#000000'
    - '#D2A34B'
    - '#E7C074'
    - '#AC7A2A'
    - '#ECDA94'
github: true
layout_spectrum: 0.596074001074372
author:
  name: LG Larsen
  email: deemiinovo@gmail.com
  url: 'https://thegrid.ai/lgsamicrafts/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a005494f-5120-4ebb-9ca2-85c83510492f.jpg
name: LGsamiCrafts
url: 'https://thegrid.ai/lgsamicrafts/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: ShopMii
    id: 969ea01e-a4f7-41ca-bfef-233bbdae1b84
    type: content
  - name: CONTACT
    id: 4d8cf57f-ec7d-456d-a820-f5487bb46de6
    type: content
  - name: Sámi DUODJI
    id: 644f518f-1e45-447a-a84c-96a4aebaa71f
    type: content
  - name: The Story
    id: 11b9b616-ab08-446d-a84b-649750ab0357
    type: content
  - name: MiiCrafts
    id: 7df6d292-1682-48bf-9e23-472b3bf3196b
    type: content
  - name: SHOWRooM
    id: f9fca674-77fa-454a-a61f-7e33634e5c3a
    type: content
  - name: Taste of Colors
    id: 924a7386-0ff4-4e6f-9579-9e905885118e
    type: content
  - name: Materials
    id: 90d06081-35cb-4b2b-9ca0-4bf7960e948d
    type: content
  - name: 'Inspiration '
    id: dc346f9e-1661-4f33-90e3-a2d4637ac6a9
    type: content
  - name: Sizes & Custom made
    id: aa97cad3-58a0-4fcd-ad74-c2da43cbadf3
    type: content
  - name: Delivery & Returns
    id: d6acc686-a159-45b0-86b7-f6f59c374dba
    type: content
  - name: 'LEATHER colors :::: home'
    url: 'https://thegrid.ai/leather-colors/'
    type: external
  - name: 'LGsignD :: home'
    url: 'https://thegrid.ai/lgsignd/'
    type: external
  - name: 'OurFriends :: home'
    url: 'https://thegrid.ai/ourfriends/'
    type: external
  - name: 'LG :: home'
    url: 'https://thegrid.ai/lg-larsen/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d1f0845-35ed-431f-87ca-41e5db2b233d.jpg
title: >-
  Selection of Handcrafted Traditional Lapland Jewelry & Accessories. Authentic
  Sami Leather Bracelets
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7df8029-35a3-4bab-a45c-795a9dc29f2d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7df8029-35a3-4bab-a45c-795a9dc29f2d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/415c40ba-0dbe-4dc2-ae08-14e71f68d5b0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/415c40ba-0dbe-4dc2-ae08-14e71f68d5b0.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Jewels that belong to Eternity
purpose:
  - type: external
    url: 'https://thegrid.ai/leather-colors/'
    label: LEATHER colors
  - type: external
    url: 'https://thegrid.ai/lgsamicrafts/contact/'
    label: CONTACTmii
