typography_spectrum: 0.9332455788390471
color:
  brandStrength: 0.5269773786166443
  lightness: 0.2560679254186626
  saturation: 0.3108205722229057
  rhythmicContrast: 0.9952563867504054
  brandColors:
    - '#000000'
    - '#D2A34B'
    - '#E7C074'
    - '#AC7A2A'
    - '#ECDA94'
github: true
layout_spectrum: 0.596074001074372
author:
  name: LG Larsen
  email: l.g.samicrafts@gmail.com
  url: 'https://thegrid.ai/lgsamicrafts/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2590a81b-2ebf-4e3e-b9cf-608de09cf45e.jpg
name: LGsamiCrafts
url: 'https://thegrid.ai/lgsamicrafts/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: ShopMii
    id: 969ea01e-a4f7-41ca-bfef-233bbdae1b84
    type: content
  - name: Contact Mii
    id: 4d8cf57f-ec7d-456d-a820-f5487bb46de6
    type: content
  - name: Sámi DUODJI
    id: 644f518f-1e45-447a-a84c-96a4aebaa71f
    type: content
  - name: The Story
    id: 11b9b616-ab08-446d-a84b-649750ab0357
    type: content
  - name: MiiCrafts
    id: dff68381-b8ca-428b-88ab-56849ac52239
    type: content
  - name: Taste of Colors
    id: 924a7386-0ff4-4e6f-9579-9e905885118e
    type: content
  - name: Materials
    id: 90d06081-35cb-4b2b-9ca0-4bf7960e948d
    type: content
  - name: Leather Colors
    url: 'https://thegrid.ai/leather-colors/'
    type: external
  - name: 'Inspiration '
    id: dc346f9e-1661-4f33-90e3-a2d4637ac6a9
    type: content
  - name: Custom made & Sizes
    id: aa97cad3-58a0-4fcd-ad74-c2da43cbadf3
    type: content
  - name: Delivery & Returns
    id: d6acc686-a159-45b0-86b7-f6f59c374dba
    type: content
  - name: LGsignD & Dee
    url: 'https://thegrid.ai/lgsignd/'
    type: external
  - name: LG -the Creator
    url: 'https://thegrid.ai/lg-larsen/'
    type: external
  - name: OurFriends
    url: 'https://thegrid.ai/ourfriends/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a9bd94d5-2035-4edb-b963-2415b369c360.jpg
title: >-
  Selection of Handcrafted Traditional Lapland Jewelry and Accessories.
  Authentic Sami Leather Bracelets
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/98e4f82d-7c0a-40eb-9009-4a23d62c6c72.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/98e4f82d-7c0a-40eb-9009-4a23d62c6c72.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8714c480-9b6f-415f-813d-79b0b870eb0f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8714c480-9b6f-415f-813d-79b0b870eb0f.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Timeless with a Story
purpose:
  - type: external
    url: 'http://lgsignd.storenvy.com/'
    label: ShopMii
  - type: external
    url: 'https://www.facebook.com/CraftMii/'
    label: Mii on Facebook
